schema = 3

[mod]
  [mod.'github.com/NimbleMarkets/ntcharts']
    version = 'v0.3.1'
    hash = 'sha256-ZybI8VrsxgK890OYFJazgFnNR6bGi4suowVHd1+XJlM='

  [mod.'github.com/alecthomas/chroma/v2']
    version = 'v2.20.0'
    hash = 'sha256-rL1mJS8fCltcii9w/efyyE4iyzogyjP+N80lE3CuzVE='

  [mod.'github.com/atotto/clipboard']
    version = 'v0.1.4'
    hash = 'sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/aymerick/douceur']
    version = 'v0.2.0'
    hash = 'sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE='

  [mod.'github.com/charmbracelet/bubbles']
    version = 'v0.21.0'
    hash = 'sha256-cfjUHgy9eq5SretTHuYuRaeeT6QmJYQBB9dsI8QSnW0='

  [mod.'github.com/charmbracelet/bubbletea']
    version = 'v1.3.6'
    hash = 'sha256-79MpQk+92RDXnNc2hSct8EDf0AhV6MZpvFMmmrVC/bs='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.2.3-0.20250311203215-f60798e515dc'
    hash = 'sha256-D9E/bMOyLXAUVOHA1/6o3i+vVmLfwIMOWib6sU7A6+Q='

  [mod.'github.com/charmbracelet/glamour']
    version = 'v1.0.0'
    hash = 'sha256-1sGgVA3QXJ2P5c/DNMb7R0HFG1X5vz9nmDhLrzKdgMw='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.1-0.20250404203927-76690c660834'
    hash = 'sha256-CwS1AyoRsPOFA4SrC0CTtwLnbg57FmmSW/mvVQUFYcc='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.10.2'
    hash = 'sha256-+JMWFbgv/5Wl2UERKxY4p5oayCRgJEDZpt2ACu3oG1o='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.13'
    hash = 'sha256-ubgBd82jcS5L4i6rCFLOB1BXGrDEu6wWlciJA0gsH2g='

  [mod.'github.com/charmbracelet/x/exp/slice']
    version = 'v0.0.0-20250327172914-2fdc97757edf'
    hash = 'sha256-C1tksnevc/RdytJRQg5LQ0+VVSWlTwbNGic649m6E1Q='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.1'
    hash = 'sha256-VBkCZLI90PhMasftGw3403IqoV7d3E5WEGAIVrN5xQM='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.1'
    hash = 'sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.11.5'
    hash = 'sha256-jN5+2ED+YbIoPIuyJ4Ou5pqJb2w1uNKzp5yTjKY6rEQ='

  [mod.'github.com/emicklei/go-restful/v3']
    version = 'v3.12.2'
    hash = 'sha256-eQ0qtVH7c5jgqB7F9B17GhZujYelBA2g9KwpPuSS0sE='

  [mod.'github.com/erikgeiser/coninput']
    version = 'v0.0.0-20211004153227-1c3628e74d0f'
    hash = 'sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.9.0'
    hash = 'sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g='

  [mod.'github.com/fxamacker/cbor/v2']
    version = 'v2.9.0'
    hash = 'sha256-/IZK76MRCrz9XCiilieH5tKaLnIWyPJhwxDoVKB8dFc='

  [mod.'github.com/go-logr/logr']
    version = 'v1.4.3'
    hash = 'sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA='

  [mod.'github.com/go-openapi/jsonpointer']
    version = 'v0.21.0'
    hash = 'sha256-bB8XTzo4hzXemi8Ey3tIXia3mfn38bvwIzKYLJYC650='

  [mod.'github.com/go-openapi/jsonreference']
    version = 'v0.20.2'
    hash = 'sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE='

  [mod.'github.com/go-openapi/swag']
    version = 'v0.23.0'
    hash = 'sha256-D5CzsSQ3SYJLwXT6BDahnG66LI8du59Dy1mY4KutA7A='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.4.0'
    hash = 'sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE='

  [mod.'github.com/gogo/protobuf']
    version = 'v1.3.2'
    hash = 'sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c='

  [mod.'github.com/google/gnostic-models']
    version = 'v0.7.0'
    hash = 'sha256-sxShRxqOUVlz9IkAz0C/NP/7CmLBW3ffwoZTdh+rIOc='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/gorilla/css']
    version = 'v1.0.1'
    hash = 'sha256-6JwNHqlY2NpZ0pSQTyYPSpiNqjXOdFHqrUT10sv3y8A='

  [mod.'github.com/grpc-ecosystem/grpc-gateway/v2']
    version = 'v2.26.3'
    hash = 'sha256-j/nyE8OgiwZ1YP0h3gmmxY1Fx4GDMCohi9g9kgNz4U8='

  [mod.'github.com/hashicorp/golang-lru/v2']
    version = 'v2.0.7'
    hash = 'sha256-t1bcXLgrQNOYUVyYEZ0knxcXpsTk4IuJZDjKvyJX75g='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/jaeyo/go-drain3']
    version = 'v0.1.2'
    hash = 'sha256-mBQensNJV8/yKb8cqJTk7QG9B8PwN3NoZcWmvSv3vPo='

  [mod.'github.com/josharian/intern']
    version = 'v1.0.0'
    hash = 'sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0='

  [mod.'github.com/json-iterator/go']
    version = 'v1.1.12'
    hash = 'sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM='

  [mod.'github.com/lrstanley/bubblezone']
    version = 'v0.0.0-20240914071701-b48c55a5e78e'
    hash = 'sha256-FoYUk7NlM5r1yYuhVPVSj72dWVHX1gb6v8Doqw0jx3I='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.3.0'
    hash = 'sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU='

  [mod.'github.com/mailru/easyjson']
    version = 'v0.7.7'
    hash = 'sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-localereader']
    version = 'v0.0.1'
    hash = 'sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.17'
    hash = 'sha256-Xeb3F+WZhyhEWNKuWRm/umc2FolXYHtbi3QoPfDPtaA='

  [mod.'github.com/microcosm-cc/bluemonday']
    version = 'v1.0.27'
    hash = 'sha256-EZSya9FLPQ83CL7N2cZy21fdS35hViTkiMK5f3op8Es='

  [mod.'github.com/modern-go/concurrent']
    version = 'v0.0.0-20180306012644-bacd9c7ef1dd'
    hash = 'sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo='

  [mod.'github.com/modern-go/reflect2']
    version = 'v1.0.3-0.20250322232337-35a7c28c31ee'
    hash = 'sha256-0pkWWZRB3lGFyzmlxxrm0KWVQo9HNXNafaUu3k+rE1g='

  [mod.'github.com/muesli/ansi']
    version = 'v0.0.0-20230316100256-276c6243b2f6'
    hash = 'sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/reflow']
    version = 'v0.3.0'
    hash = 'sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/munnerz/goautoneg']
    version = 'v0.0.0-20191010083416-a7dc8b61c822'
    hash = 'sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.3'
    hash = 'sha256-fE++SVgnCGdnFZoROHWuYjIR7ENl7k9KKxQrRTquv/o='

  [mod.'github.com/pkg/errors']
    version = 'v0.9.1'
    hash = 'sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.0'
    hash = 'sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.7.0'
    hash = 'sha256-ZmaGOKHDw18jJqdkwQwSpUT11F9toR6KPs3241TONeY='

  [mod.'github.com/sourcegraph/conc']
    version = 'v0.3.0'
    hash = 'sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko='

  [mod.'github.com/spf13/afero']
    version = 'v1.12.0'
    hash = 'sha256-TX3DcyAdrXqf+TxmEz4TilWQo2Y4hcBXOeRY6BjDp+s='

  [mod.'github.com/spf13/cast']
    version = 'v1.7.1'
    hash = 'sha256-BjX0aY/PC37gIdMc7JhMgvhWFsksGdAcp2FgzpuvkPo='

  [mod.'github.com/spf13/cobra']
    version = 'v1.9.1'
    hash = 'sha256-dzEqquABE3UqZmJuj99244QjvfojS8cFlsPr/MXQGj0='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.6'
    hash = 'sha256-NjrK0FZPIfO/p2xtL1J7fOBQNTZAPZOC6Cb4aMMvhxI='

  [mod.'github.com/spf13/viper']
    version = 'v1.20.1'
    hash = 'sha256-gbCM0k7RAlvn7jpSuWB2LX5Nip9vgwsPNGbDXTI7JvM='

  [mod.'github.com/stretchr/testify']
    version = 'v1.11.1'
    hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'github.com/x448/float16']
    version = 'v0.8.4'
    hash = 'sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.7.13'
    hash = 'sha256-vBCxZrPYPc8x/nvAAv3Au59dCCyfS80Vw3/a9EXK7TE='

  [mod.'github.com/yuin/goldmark-emoji']
    version = 'v1.0.6'
    hash = 'sha256-+d6bZzOPE+JSFsZbQNZMCWE+n3jgcQnkPETVk47mxSY='

  [mod.'go.opentelemetry.io/proto/otlp']
    version = 'v1.7.0'
    hash = 'sha256-wqmUA6XGjODfuTCRQs32tYFkvO717ZGyZYZFcbNHvLw='

  [mod.'go.uber.org/multierr']
    version = 'v1.11.0'
    hash = 'sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0='

  [mod.'go.yaml.in/yaml/v2']
    version = 'v2.4.2'
    hash = 'sha256-oC8RWdf1zbMYCtmR0ATy/kCkhIwPR9UqFZSMOKLVF/A='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

  [mod.'golang.org/x/net']
    version = 'v0.48.0'
    hash = 'sha256-oZpddsiJwWCH3Aipa+XXpy7G/xHY5fEagUSok7T0bXE='

  [mod.'golang.org/x/oauth2']
    version = 'v0.34.0'
    hash = 'sha256-5eqpGGxJ7FJsPmfRek6roeGmkWHBMJaWYXyz8gXJsS4='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.39.0'
    hash = 'sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U='

  [mod.'golang.org/x/term']
    version = 'v0.38.0'
    hash = 'sha256-46mX91XGJqii6SUESiU5mLVJDBOfKYCp+408m91hrMw='

  [mod.'golang.org/x/text']
    version = 'v0.32.0'
    hash = 'sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs='

  [mod.'golang.org/x/time']
    version = 'v0.9.0'
    hash = 'sha256-ipaWVIk1+DZg0rfCzBSkz/Y6DEnB7xkX2RRYycHkhC0='

  [mod.'google.golang.org/genproto/googleapis/api']
    version = 'v0.0.0-20251202230838-ff82c1b0f217'
    hash = 'sha256-z0OqsPMjhZ8fNmUbcDfi5Q49hBcutKX8lyzW1mLBTec='

  [mod.'google.golang.org/genproto/googleapis/rpc']
    version = 'v0.0.0-20251202230838-ff82c1b0f217'
    hash = 'sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA='

  [mod.'google.golang.org/grpc']
    version = 'v1.79.3'
    hash = 'sha256-mO9ZI8ONBMEBTlrwIPeQMfb3C9ru5zPb26P+uG/pIzY='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.10'
    hash = 'sha256-gUrj1qSpjcpRKCBnrYlKMm+P0OSh7B/8EBREstwhD1w='

  [mod.'gopkg.in/evanphx/json-patch.v4']
    version = 'v4.12.0'
    hash = 'sha256-rUOokb3XW30ftpHp0fsF2WiJln1S0FSt2El7fTHq3CM='

  [mod.'gopkg.in/inf.v0']
    version = 'v0.9.1'
    hash = 'sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

  [mod.'k8s.io/api']
    version = 'v0.34.2'
    hash = 'sha256-8TpPB07Dh6REOxYzT78OGLCV1iTZlMVzEQCzmpA4Q3U='

  [mod.'k8s.io/apimachinery']
    version = 'v0.34.2'
    hash = 'sha256-y6GVugdaX81lHwVWgDgFoIi/v6K9A3YC2kKlGUritVU='

  [mod.'k8s.io/client-go']
    version = 'v0.34.2'
    hash = 'sha256-ELhaXsMrieNn0ms84n5kL9QlNDXQ2u8xpbny+bTvdZg='

  [mod.'k8s.io/klog/v2']
    version = 'v2.130.1'
    hash = 'sha256-n5vls1o1a0V0KYv+3SULq4q3R2Is15K8iDHhFlsSH4o='

  [mod.'k8s.io/kube-openapi']
    version = 'v0.0.0-20250710124328-f3f2b991d03b'
    hash = 'sha256-0v0MN67pora3UCA8vXSJDgkosx/1RaB2HkjUnwdVLbY='

  [mod.'k8s.io/utils']
    version = 'v0.0.0-20250604170112-4c0f3b243397'
    hash = 'sha256-USPKRYYKfbhQWU0CgT/8V1hdBirWjmhTZvJCuuUlNFo='

  [mod.'nhooyr.io/websocket']
    version = 'v1.8.17'
    hash = 'sha256-YIYdIz3KR3j3ykT/TSOoftwkCoZdX1/bUtlXm3RjfoQ='

  [mod.'sigs.k8s.io/json']
    version = 'v0.0.0-20241014173422-cfa47c3a1cc8'
    hash = 'sha256-dkegDkyjp/niYirIdhbQrBYt/uttCZQAfsBzKSzOMh0='

  [mod.'sigs.k8s.io/randfill']
    version = 'v1.0.0'
    hash = 'sha256-xldQxDwW84hmlihdSOFfjXyauhxEWV9KmIDLZMTcYNo='

  [mod.'sigs.k8s.io/structured-merge-diff/v6']
    version = 'v6.3.0'
    hash = 'sha256-2EqUZSaHUhwTrdjoZuv+Z99tZYrX1E6rxf2ejeKd2BM='

  [mod.'sigs.k8s.io/yaml']
    version = 'v1.6.0'
    hash = 'sha256-49hg7IVPzwxeovp+HTMiWa/10NMMTSTjAdCmIv6p9dw='
